### ISSUE TITLE
Question: get edges within one api call

### ISSUE THREAD

**Issue by nicolascochin** [facebook/facebook-ruby-ads-sdk#42]
Hi, 

Is it possible to get the edge's data within a single api call ? 

For example, I'd like to retrieve the ads within campaigns from my ad_account. 
The graphql query i'd like : `act_XXX?fields=campaigns{name,ads{name}}`

I'm able to retrieve the campaigns `ad_account.campaigns(fields: [:name])` but I can't manage to get the ads. 

How can we do such a query?

**Comment by mattnwa** [comment]
I'm just now having this same dream @nicolascochin.  Any chance you figured this out and have any clues?
